/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC->AHB1ENR |=(1<<1);
	RCC->AHB1ENR |=(1<<2);

	GPIOB->MODER &= ~(3<<28);
	GPIOB->MODER |=(1<<28);


	GPIOB->MODER &= ~(3<<26);
	GPIOB->MODER |=(1<<26);


	GPIOB->MODER &= ~(3<<30);
	GPIOB->MODER |=(1<<30);


	GPIOC->MODER &= ~(3<<12);
	GPIOC->MODER |=(1<<12);




    /* Loop forever */
	for(;;)
	{
		int i;

	    GPIOB->ODR &=~(1<<13);
	    for(i=0;i<300000;i++);
	    GPIOB->ODR |=(1<<13);
	    for(i=0;i<300000;i++);

		GPIOB->ODR &=~(1<<14);
		for(i=0;i<300000;i++);
		GPIOB->ODR |=(1<<14);
		for(i=0;i<300000;i++);

		GPIOB->ODR &=~(1<<15);
		for(i=0;i<300000;i++);
		GPIOB->ODR |=(1<<15);
		for(i=0;i<300000;i++);

		GPIOC->ODR &=~(1<<6);
		for(i=0;i<300000;i++);
		GPIOC->ODR |=(1<<6);
		for(i=0;i<300000;i++);

	}

}
